Merge workflows and scripts from main.

diff --git a/scripts/build_all_packages b/scripts/build_all_packages
--- a/scripts/build_all_packages
+++ b/scripts/build_all_packages
@@ -2,37 +2,59 @@
 # SPDX-License-Identifier: GPL-2.0-or-later
 # Copyright (C) 2025 SteamFork (https://github.com/SteamFork)
 
+SCRIPT_NAME=$(basename "$0")
+
+# Log function for consistent output
+log() {
+  local msg="$1"
+  echo "$(date +'%Y-%m-%d %H:%M:%S') - ${SCRIPT_NAME}: ${msg}"
+}
+
 # Source the environment variables from the Makefile
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 MAKEFILE_PATH="${SCRIPT_DIR}/../Makefile"
 eval $(make -s -f "${MAKEFILE_PATH}" env)
 
-# Refresh the GPG key periodically
-refresh_gpg_key_periodically() {
-    while true; do
-        gpg --batch --yes --pinentry-mode loopback --list-keys > /dev/null
-        sleep 1800  # Refresh every 30 minutes
-    done
-}
-
-# Start the GPG key refresh in the background
-refresh_gpg_key_periodically &
-
 PACKAGES_LIST="${SCRIPT_DIR}/../metadata/packages.list"
 
+# Load packages list into an array
+mapfile -t packages < "$PACKAGES_LIST"
+
 # Read the packages list and build each package with dependencies
-while IFS= read -r line; do
-    if [[ "$line" == local:* ]]; then
-        PKG="${line#local:}"
-        REPO_FLAG="local"
-    elif [[ "$line" == aur:* ]]; then
-        PKG="${line#aur:}"
-        REPO_FLAG="aur"
-    else
-        echo "Unknown package type: $line"
+for ((i = 0; i < ${#packages[@]}; i++)); do
+    line="${packages[$i]}"
+
+    # Use awk to parse the line
+    PKG=$(echo "$line" | awk -F'|' '{print $2}')
+    REPO_FLAG=$(echo "$line" | awk -F'|' '{print $1}')
+
+    if [[ -z "$PKG" || -z "$REPO_FLAG" ]]; then
+        log "Unable to parse data from line: $line"
         continue
     fi
 
-    echo "Building package: $PKG (repo: $REPO_FLAG)"
+    # Check if the package is in the correct order to trap conditions
+    # where a package may be skipped when building.
+    if [[ "$line" != "${packages[$i]}" ]]; then
+        log "Error: Package $PKG is out of order. Exiting."
+        exit 1
+    fi
+
+    log "Clearing pacman cache..."
+    yes | sudo pacman -Scc --noconfirm
+    if [ $? -ne 0 ]; then
+        log "Error: Failed to clear pacman cache."
+        exit 1
+    fi
+
+    log "Building package: $PKG (repo: $REPO_FLAG)"
     "${SCRIPT_DIR}/build_package" --repo ${REPO_FLAG} "$PKG"
-done < "$PACKAGES_LIST"
+    if [ $? -ne 0 ]; then
+        log "Error: Failed to build package $PKG. Exiting."
+        exit 1
+    fi
+
+    log "Successfully built package: $PKG"
+done
+
+log "All packages built successfully."
