Update burnimage to support 3.7

diff --git a/scripts/burnimage b/scripts/burnimage
--- a/scripts/burnimage
+++ b/scripts/burnimage
@@ -4,11 +4,18 @@
 # Copyright (C) 2024 SteamFork (https://github.com/SteamFork)
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
 eval $(make -s -f "${SCRIPT_DIR}/../Makefile" env)
 
-IMAGE_PATH="release/images/rel/images"
-source ${IMAGE_PATH}/latest_rel.releasemeta
+VERSION=${1:-3.7}
+BRANCH=${2:-stable}
+IMAGE_PATH="release/images/${VERSION}/${BRANCH}"
+if [ -f ${IMAGE_PATH}/latest_${BRANCH}.releasemeta ]
+then
+  source ${IMAGE_PATH}/latest_${BRANCH}.releasemeta
+else
+  echo "Release not found (${VERSION}/${BRANCH})."
+  exit 1
+fi
 ARCH="x86_64"
 ISO="${IMAGE_PATH}/installer/${IMAGEFILE//_/-}-${ARCH}.iso"
 
