Sync gamescope-session with upstream.

diff --git a/PKGBUILD/gamescope/gamescope-session b/PKGBUILD/gamescope/gamescope-session
--- a/PKGBUILD/gamescope/gamescope-session
+++ b/PKGBUILD/gamescope/gamescope-session
@@ -24,14 +24,14 @@ export GAMESCOPE_PATCHED_EDID_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/
 # meant to let this happen is missing the color range...
 # So just workaround this with an ENV var that Remote Play Together
 # and Gamescope will use for now.
-export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
+export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT709_Full
+
+export STEAM_GAMESCOPE_HDR_SUPPORTED=1
 
 # Workaround older versions of vkd3d-proton setting this
 # too low (desc.BufferCount), resulting in symptoms that are potentially like
 # swapchain starvation.
 export VKD3D_SWAPCHAIN_LATENCY_FRAMES=3
-
-export STEAM_GAMESCOPE_HDR_SUPPORTED=1
 
 # Make path to gamescope mode save file.
 mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
@@ -54,36 +54,13 @@ echo "no_display" > "$MANGOHUD_CONFIGFILE"
 mkdir -p "$(dirname "$RADV_FORCE_VRS_CONFIG_FILE")"
 echo "1x1" > "$RADV_FORCE_VRS_CONFIG_FILE"
 
-# Expose all threads and cores properly
-unset TOPOLOGY
-export THREADS=$(nproc)
-for ((i = 0; i < THREADS; ++i)); do
-    TOPOLOGY+="${i},"
-done
-export CPU_TOPOLOGY=${TOPOLOGY%?}
-echo "${THREADS} available threads on CPU, setting \"${THREADS}:${CPU_TOPOLOGY}\" CPU topology for Wine"
-export WINE_CPU_TOPOLOGY=${THREADS}:${CPU_TOPOLOGY}
+# Let's try this across the board to see if it breaks anything
+# Helps performance in HZD, Cyberpunk, at least
+# Expose 8 physical cores, instead of 4c/8t
+export WINE_CPU_TOPOLOGY=8:0,1,2,3,4,5,6,7
 
 # To expose vram info from radv's patch we're including
 export WINEDLLOVERRIDES=dxgi=n
-
-# Workaround for steam getting killed immediatly during reboot
-# See: jupiter/tasks/-/issues/280
-export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
-if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
-	/usr/bin/steamos-polkit-helpers/steamos-reboot-now
-	sudo -n reboot
-fi
-
-# Workaround for steam getting killed immediatly during shutdown
-# Same idea as reboot sentinel above
-export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
-if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
-	/usr/bin/steamos-polkit-helpers/steamos-poweroff-now
-	sudo -n poweroff
-fi
 
 # Enable dynamic backlight, we have the kernel patch to disable events
 export STEAM_ENABLE_DYNAMIC_BACKLIGHT=1
@@ -146,7 +123,7 @@ export STEAM_GAMESCOPE_FANCY_SCALING_SUPPORT=1
 export STEAM_GAMESCOPE_COLOR_MANAGED=1
 export STEAM_GAMESCOPE_VIRTUAL_WHITE=1
 
-HDMI-CEC support
+# HDMI-CEC support
 export STEAM_ENABLE_CEC=1
 
 # Set input method modules for Qt/GTK that will show the Steam keyboard
@@ -290,6 +267,68 @@ function get_active_display() {
 	done
 }
 
+cleanup_loop() {
+    if [ -n "$pid" ]; then
+        kill "$pid"
+    fi
+    exit 0
+}
+
+# Make sure we stop the loop and cleanup properly, with a wait for our
+# children, when we have a recurring background command.
+loop_background() {
+    (
+        pid=
+        trap cleanup_loop TERM
+        while true; do
+            "$@" &
+            pid=$!
+            wait "$pid"
+        done
+    ) &
+}
+
+print_children() {
+    ps h -o pid --ppid "$1" | sed 's/^[[:space:]]*//'
+}
+
+send_signals() {
+    kill -TERM "$@"
+}
+
+cleanup() {
+    local timeout="$1"
+    shift
+    local children=("$@")
+    local sleep_pid pid ret
+
+    # Start a background sleep as a timeout because we don't trust it
+    sleep "$timeout" &
+    sleep_pid=$!
+
+    for pid in "${children[@]}"; do
+        if ! kill -0 "$pid" 2>/dev/null; then
+            continue
+        fi
+
+        # Wait for child or the sleep to finish for timeout purposes
+        ret=0
+        wait -np finished_pid "$pid" "$sleep_pid" || ret=$?
+
+        # Our sleep command finished; we timed out
+        if [[ "$finished_pid" == "$sleep_pid" ]]; then
+            return 2
+        fi
+
+        # Signal received by wait when already in cleanup; bail out
+        if (( ret > 128 )); then
+            return 1
+        fi
+    done
+
+    kill "$sleep_pid"
+}
+
 ### Default to the current version of Gamescope.
 GAMESCOPE_BINARY="gamescope"
 
@@ -305,14 +344,14 @@ if [ -n "${HAS_INTEL}" ] && \
    [ -z "${HAS_AMD}" ]
 then
 	### This is an Intel IPU without an AMD GPU.
-        export ENABLE_GAMESCOPE_WSI=0
-        export INTEL_DEBUG=norbc
-        export mesa_glthread=true
+	export ENABLE_GAMESCOPE_WSI=0
+	export INTEL_DEBUG=norbc
+	export mesa_glthread=true
 elif [ -n "${HAS_LEGACY}" ]
 then
 	### This is a device with an AMD GPU that is Polaris or older.
-        export mesa_glthread=true
-        GAMESCOPE_BINARY="gamescope-legacy"
+	export mesa_glthread=true
+	GAMESCOPE_BINARY="gamescope-legacy"
 fi
 
 ### Set up quirks for the device.  Do this late so we can override any detected parameters.
@@ -336,7 +375,6 @@ sudo udevadm trigger && ${GAMESCOPE_BINARY} \
 	--cursor-scale-height 720 \
 	-e -R "$socket" -T "$stats" \
 	-O '*',${GAMESCOPE_DISPLAY} \
-	"${mura_args[@]}" \
 	&
 gamescope_pid="$!"
 
@@ -351,14 +389,16 @@ else
 	# SDDM will restart us
 fi
 
-xbindkeys -f /etc/xbindkeysrc
+xbindkeys -n -f /etc/xbindkeysrc &
 
 steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
 
 # Input method support
-/usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
+/usr/bin/ibus-daemon -r --panel=disable --emoji-extension=disable &
 
 # steamargs+=("-steamfs")
+
+loop_background /usr/lib/hwsupport/powerbuttond
 
 short_session_tracker_file="/tmp/steamos-short-session-tracker"
 short_session_duration=60
@@ -368,33 +408,60 @@ SECONDS=0
 short_session_count=$(< "$short_session_tracker_file" wc -l)
 
 if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-	# TODO could detect if we're in the devkit case below and undo that instead
-	# instead of resetting the wrong thing
-	# also could print full list of files and sizes in the Steam dir and save as a diagnostic report
 	echo >&2 "gamescope-session: detected broken Steam, bootstrapping from OS copy..."
 	# at this point, might as well make sure we won't relaunch on a sideloaded build
 	rm -f -- "$HOME/devkit-game/devkit-steam"
 	mkdir -p ~/.local/share/Steam
 	# remove some caches and stateful things known to cause Steam to fail to start if corrupt
 	rm -rf --one-file-system ~/.local/share/Steam/config/widevine
+	# cleanup the steam config dir, i.e. ~/.steam. We should try to preserve registry.vdf if possible
+	steam_config_dir="$HOME/.steam"
+	steam_config_backup_dir="$HOME/dot-steam.bak.$(date +%s)"
+	registry_vdf="$steam_config_dir/registry.vdf"
+	registry_backup_vdf="$steam_config_backup_dir/.steam/registry.vdf"
+	mv "$steam_config_dir" "$steam_config_backup_dir"
+	mkdir -p "$steam_config_dir"
+	cp -f "$registry_backup_vdf" "$registry_vdf" || true
 	# restore clean copy of binaries from RO partition
 	tar xf /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
 	# rearm
 	rm "$short_session_tracker_file"
 fi
 
+steam_notif_daemon &
+galileo-mura-setup &
+loop_background mangoapp
+
 if [[ -x $HOME/devkit-game/devkit-steam ]]; then
-	steam_notif_daemon &
-	(while true; do
-		mangoapp
-	done) &
-	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}"
+	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}" &
+	steam_wrapper_pid=$!
 else
-	steam_notif_daemon &
-	(while true; do
-		mangoapp
-	done) &
-	steam "${steamargs[@]}"
+	steam "${steamargs[@]}" &
+	steam_wrapper_pid=$!
+fi
+
+kill_steam() {
+	# We need to kill the children of the wrapper, since the wrapper
+	# lacks signal handling (and so killing it does not properly kill
+	# steam)
+	readarray -t pids < <(print_children "$steam_wrapper_pid")
+
+	if [[ "${#pids[@]}" -gt 0 ]]; then
+		kill -TERM "${pids[@]}"
+	else
+		kill -TERM "$steam_wrapper_pid"
+	fi
+}
+
+trap kill_steam TERM
+
+wait "$steam_wrapper_pid"
+exit_code=$?
+
+trap - TERM
+
+if (( exit_code > 128 )); then
+	wait "$steam_wrapper_pid"
 fi
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
@@ -403,19 +470,16 @@ else
 	rm "$short_session_tracker_file"
 fi
 
-# Ask gamescope to exit nicely
-kill $gamescope_pid
+# Ask all children to exit nicely, now that steam has exited
+readarray -t children < <(print_children $$)
 
-# Start a background sleep for five seconds because we don't trust it
-sleep 5 &
-sleep_pid=$!
+send_signals "${children[@]}"
 
-# Wait for gamescope or the sleep to finish for timeout purposes
-ret=0
-wait -n $gamescope_pid $sleep_pid || ret=$?
+cleanup 5 "${children[@]}"
+cleanup_status=$!
 
 # If we get a SIGTERM/etc while waiting this happens.  Proceed to kill -9 everything but complain
-if [[ $ret = 127 ]]; then
+if (( cleanup_status == 1 )); then
 	echo >&2 "gamescope-session: Interrupted while waiting on teardown, force-killing remaining tasks"
 fi
 
@@ -423,14 +487,14 @@ fi
 # to exit in time or we hit the interrupt case above)
 for job in $(jobs -p); do
 	# Warn about unexpected things
-	if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
+	if (( cleanup_status == 1 )) && [[ $job = "$gamescope_pid" ]]; then
 		echo >&2 "gamescope-session: gamescope timed out while exiting, killing"
-	elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
+	elif (( cleanup_status == 1 )) && [[ $job != "$sleep_pid" ]]; then
 		echo >&2 "gamescope-session: unexpected background pid $job at teardown: "
 		# spew some debug about it
 		ps -p "$job" >&2
 	fi
-	kill -9 "$job"
+	kill -KILL "$job"
 done
 
 # This should just be waiting on kill -9'd things. Another signal will cause us to give up, but we should be a little
